import { useState, useEffect } from 'react';
import { groupKpiRows, KpiRow, ReportBlockView } from '../components/ReportBlocks.jsx';

// PUBLIC report viewer — the /r/:token share page. No Pulse login: the token is
// the capability, so stakeholders (sponsors, partners, execs) open it straight
// from an email or chat. Renders the FROZEN snapshot (numbers never drift) with
// the client's branding, mobile-first, with a Download-PDF action. Mounted
// outside the auth'd router (see App.jsx), like the /embed/* pages. Block
// rendering is shared with the editor canvas — see components/ReportBlocks.jsx.
export default function ReportViewPage({ token }) {
  const [data, setData] = useState(null);
  const [error, setError] = useState('');
  useEffect(() => {
    fetch(`/api/public/reports/${encodeURIComponent(token)}`)
      .then(async (r) => { if (!r.ok) throw new Error((await r.json().catch(() => ({}))).error || 'This report link is invalid or has been revoked.'); return r.json(); })
      .then(setData)
      .catch((e) => setError(e.message));
  }, [token]);
  useEffect(() => { if (data?.title) document.title = data.title; }, [data]);

  if (error) return <Shell><div style={{ ...cardS, textAlign: 'center', color: '#6b6b70', fontSize: 14 }}>{error}</div></Shell>;
  if (!data) return <Shell><div style={{ textAlign: 'center', color: '#a1a1a6', fontSize: 14, padding: 40 }}>Loading report…</div></Shell>;

  const accent = /^#[0-9a-fA-F]{6}$/.test(data.branding?.primary || '') ? data.branding.primary : '#FF2D55';
  const dateLine = data.generatedAt ? new Date(data.generatedAt).toLocaleDateString('en-ZA', { day: 'numeric', month: 'long', year: 'numeric' }) : '';

  return (
    <Shell>
      <header style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 14, flexWrap: 'wrap' }}>
        {data.branding?.logo
          ? <img src={data.branding.logo} alt={data.branding?.name || ''} style={{ maxHeight: 40, maxWidth: 190 }} />
          : <span style={{ fontSize: 16, fontWeight: 800, letterSpacing: '-0.02em', color: '#111' }}>{data.branding?.name || ''}</span>}
        <span style={{ flex: 1 }} />
        <a href={`/api/public/reports/${encodeURIComponent(token)}/pdf`} target="_blank" rel="noreferrer"
          style={{ padding: '9px 16px', background: accent, color: '#fff', borderRadius: 980, fontSize: 13, fontWeight: 700, textDecoration: 'none' }}>⬇ Download PDF</a>
      </header>
      <div style={cardS}>
        <h1 style={{ fontSize: 26, fontWeight: 800, letterSpacing: '-0.01em', color: '#111', margin: 0 }}>{data.title}</h1>
        {dateLine && <div style={{ fontSize: 13, color: '#86868b', margin: '4px 0 6px' }}>{dateLine}</div>}
        <div style={{ borderTop: `2.5px solid ${accent}`, margin: '12px 0 20px' }} />
        {groupKpiRows(data.blocks).map((r, i) => (r.kind === 'kpis'
          ? <KpiRow key={i} items={r.items} />
          : <ReportBlockView key={i} b={r.b} accent={accent} />))}
      </div>
      <footer style={{ fontSize: 12, color: '#a1a1a6', textAlign: 'center', margin: '16px 0 8px' }}>
        Generated by <span style={{ fontWeight: 700 }}>Howler&nbsp;:&nbsp;Pulse</span>
      </footer>
    </Shell>
  );
}

function Shell({ children }) {
  return (
    <div style={{ minHeight: '100dvh', background: '#f5f5f7', fontFamily: "-apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif" }}>
      <div style={{ maxWidth: 720, margin: '0 auto', padding: '24px 14px', boxSizing: 'border-box' }}>
        {children}
      </div>
    </div>
  );
}
const cardS = { background: '#ffffff', border: '1px solid rgba(128,128,128,0.16)', borderRadius: 16, padding: 'clamp(18px, 4vw, 32px)' };
