import { useState, useEffect } from 'react';

// PUBLIC report viewer — the /r/:token share page. No Pulse login: the token is
// the capability, so stakeholders (sponsors, partners, execs) open it straight
// from an email or chat. Renders the FROZEN snapshot (numbers never drift) with
// the client's branding, mobile-first, with a Download-PDF action. Mounted
// outside the auth'd router (see App.jsx), like the /embed/* pages.
export default function ReportViewPage({ token }) {
  const [data, setData] = useState(null);
  const [error, setError] = useState('');
  useEffect(() => {
    fetch(`/api/public/reports/${encodeURIComponent(token)}`)
      .then(async (r) => { if (!r.ok) throw new Error((await r.json().catch(() => ({}))).error || 'This report link is invalid or has been revoked.'); return r.json(); })
      .then(setData)
      .catch((e) => setError(e.message));
  }, [token]);
  useEffect(() => { if (data?.title) document.title = data.title; }, [data]);

  if (error) return <Shell accent="#FF2D55"><div style={{ ...cardS, textAlign: 'center', color: '#6b6b70', fontSize: 14 }}>{error}</div></Shell>;
  if (!data) return <Shell accent="#FF2D55"><div style={{ textAlign: 'center', color: '#a1a1a6', fontSize: 14, padding: 40 }}>Loading report…</div></Shell>;

  const accent = /^#[0-9a-fA-F]{6}$/.test(data.branding?.primary || '') ? data.branding.primary : '#FF2D55';
  const dateLine = data.generatedAt ? new Date(data.generatedAt).toLocaleDateString('en-ZA', { day: 'numeric', month: 'long', year: 'numeric' }) : '';

  // Consecutive KPI tiles flow together as one chip row.
  const rows = [];
  for (const b of data.blocks || []) {
    const isKpi = b.type === 'tile' && b.kind === 'kpi';
    const last = rows[rows.length - 1];
    if (isKpi && last?.kind === 'kpis') last.items.push(b);
    else if (isKpi) rows.push({ kind: 'kpis', items: [b] });
    else rows.push({ kind: 'block', b });
  }

  return (
    <Shell accent={accent}>
      <header style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 14, flexWrap: 'wrap' }}>
        {data.branding?.logo
          ? <img src={data.branding.logo} alt={data.branding?.name || ''} style={{ maxHeight: 40, maxWidth: 190 }} />
          : <span style={{ fontSize: 16, fontWeight: 800, letterSpacing: '-0.02em', color: '#111' }}>{data.branding?.name || ''}</span>}
        <span style={{ flex: 1 }} />
        <a href={`/api/public/reports/${encodeURIComponent(token)}/pdf`} target="_blank" rel="noreferrer"
          style={{ padding: '9px 16px', background: accent, color: '#fff', borderRadius: 980, fontSize: 13, fontWeight: 700, textDecoration: 'none' }}>⬇ Download PDF</a>
      </header>
      <div style={cardS}>
        <h1 style={{ fontSize: 26, fontWeight: 800, letterSpacing: '-0.01em', color: '#111', margin: 0 }}>{data.title}</h1>
        {dateLine && <div style={{ fontSize: 13, color: '#86868b', margin: '4px 0 6px' }}>{dateLine}</div>}
        <div style={{ borderTop: `2.5px solid ${accent}`, margin: '12px 0 20px' }} />
        {rows.map((r, i) => r.kind === 'kpis' ? (
          <div key={i} style={{ display: 'flex', flexWrap: 'wrap', gap: 10, margin: '4px 0 16px' }}>
            {r.items.map((k, j) => (
              <div key={j} style={{ border: '1px solid #e8e8ec', borderRadius: 12, padding: '12px 18px', minWidth: 120, flex: '0 1 auto' }}>
                <div style={{ fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em', color: '#86868b' }}>{k.title}</div>
                <div style={{ fontSize: 24, fontWeight: 800, color: '#111', marginTop: 2 }}>{k.value}</div>
              </div>
            ))}
          </div>
        ) : <Block key={i} b={r.b} accent={accent} />)}
      </div>
      <footer style={{ fontSize: 12, color: '#a1a1a6', textAlign: 'center', margin: '16px 0 8px' }}>
        Generated by <span style={{ fontWeight: 700 }}>Howler&nbsp;:&nbsp;Pulse</span>
      </footer>
    </Shell>
  );
}

function Block({ b, accent }) {
  switch (b.type) {
    case 'heading':
      return b.level === 2
        ? <h3 style={{ fontSize: 15, fontWeight: 700, color: '#111', margin: '18px 0 8px' }}>{fmt(b.text)}</h3>
        : <h2 style={{ fontSize: 19, fontWeight: 800, letterSpacing: '-0.01em', color: '#111', margin: '22px 0 10px' }}>{fmt(b.text)}</h2>;
    case 'text':
      return <p style={{ fontSize: 14.5, lineHeight: 1.65, color: '#3a3a3c', margin: '0 0 14px', whiteSpace: 'pre-wrap' }}>{fmt(b.text)}</p>;
    case 'ai': {
      const body = b.text || b.note;
      if (!body) return null;
      return (
        <div style={{ borderLeft: `3px solid ${accent}`, padding: '4px 0 4px 14px', margin: '4px 0 16px' }}>
          <div style={{ fontSize: 10.5, fontWeight: 800, letterSpacing: '0.06em', color: accent, marginBottom: 4 }}>ANALYSIS</div>
          <div style={{ fontSize: 14.5, lineHeight: 1.65, color: '#3a3a3c', whiteSpace: 'pre-wrap', fontStyle: b.text ? 'normal' : 'italic' }}>{body}</div>
        </div>
      );
    }
    case 'image': {
      const src = b.assetToken ? `/report-assets/${b.assetToken}` : b.url;
      return src ? <img src={src} alt={b.alt || ''} style={{ maxWidth: '100%', borderRadius: 10, margin: '4px 0 16px', display: 'block' }} /> : null;
    }
    case 'button':
      return b.text ? (
        <div style={{ margin: '4px 0 16px' }}>
          <a href={b.href || '#'} target="_blank" rel="noreferrer" style={{ display: 'inline-block', padding: '11px 24px', background: accent, color: '#fff', borderRadius: 980, fontSize: 13.5, fontWeight: 700, textDecoration: 'none' }}>{b.text}</a>
        </div>
      ) : null;
    case 'divider':
      return <div style={{ borderTop: '1px solid #e8e8ec', margin: '16px 0' }} />;
    case 'tile': {
      if (b.kind === 'chart') return <img src={`/report-assets/${b.assetToken}`} alt={b.title || 'Chart'} style={{ width: '100%', borderRadius: 10, margin: '4px 0 16px', display: 'block' }} />;
      if (b.kind === 'table') {
        return (
          <div style={{ margin: '4px 0 16px' }}>
            {b.title && <div style={{ fontSize: 13.5, fontWeight: 700, color: '#111', marginBottom: 6 }}>{b.title}</div>}
            <div style={{ overflowX: 'auto', WebkitOverflowScrolling: 'touch' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse', minWidth: Math.min(560, (b.columns || []).length * 110) }}>
                <thead><tr>{(b.columns || []).map((c, i) => <th key={i} style={{ textAlign: 'left', fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.04em', color: '#86868b', padding: '6px 8px', borderBottom: '1px solid #e8e8ec', whiteSpace: 'nowrap' }}>{c}</th>)}</tr></thead>
                <tbody>{(b.rows || []).map((r, i) => <tr key={i}>{r.map((v, j) => <td key={j} style={{ fontSize: 13.5, color: '#3a3a3c', padding: '7px 8px', borderBottom: '1px solid #f2f2f5' }}>{v}</td>)}</tr>)}</tbody>
              </table>
            </div>
            {b.more ? <div style={{ fontSize: 11.5, color: '#86868b', marginTop: 4 }}>… {b.more} more rows</div> : null}
          </div>
        );
      }
      if (b.kind === 'missing') return <div style={{ fontSize: 13, color: '#a1a1a6', fontStyle: 'italic', margin: '4px 0 14px' }}>{b.title} — data unavailable at generation time</div>;
      return null;
    }
    default:
      return null;
  }
}

// **bold** / *italic* — the same light author markup emailBlocks supports.
function fmt(s) {
  const out = [];
  let key = 0;
  for (const seg of String(s || '').split(/(\*\*[^*]+\*\*)/g)) {
    const b = /^\*\*([^*]+)\*\*$/.exec(seg);
    if (b) { out.push(<strong key={key++}>{b[1]}</strong>); continue; }
    for (const s2 of seg.split(/(\*[^*]+\*)/g)) {
      const i = /^\*([^*]+)\*$/.exec(s2);
      if (i) out.push(<em key={key++}>{i[1]}</em>);
      else if (s2) out.push(s2);
    }
  }
  return out;
}

function Shell({ accent, children }) {
  return (
    <div style={{ minHeight: '100dvh', background: '#f5f5f7', fontFamily: "-apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif" }}>
      <div style={{ maxWidth: 720, margin: '0 auto', padding: '24px 14px', boxSizing: 'border-box' }} data-accent={accent}>
        {children}
      </div>
    </div>
  );
}
const cardS = { background: '#ffffff', border: '1px solid rgba(128,128,128,0.16)', borderRadius: 16, padding: 'clamp(18px, 4vw, 32px)' };
