import { useState, useEffect } from 'react';
import { createPortal } from 'react-dom';

// Full-height side panel showing an AI insight that streams in live as Claude
// writes it. Rendered via a portal to document.body so it escapes the
// dashboard grid's CSS transform (otherwise position:fixed clamps to the tile).
export default function InsightModal({ tile, data, filters, onClose }) {
  const [insight, setInsight] = useState('');
  const [loading, setLoading] = useState(true); // true until first text arrives
  const [error, setError] = useState(null);

  useEffect(() => {
    const controller = new AbortController();
    setInsight('');
    setLoading(true);
    setError(null);

    (async () => {
      try {
        const res = await fetch('/api/insight', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            title: tile.title,
            visType: tile.vis?.type,
            fields: data.fields,
            rows: data.data,
            filters,
          }),
          signal: controller.signal,
        });
        if (!res.ok) {
          const j = await res.json().catch(() => ({}));
          throw new Error(j.error || `Request failed (${res.status})`);
        }
        const reader = res.body.getReader();
        const decoder = new TextDecoder();
        let acc = '';
        for (;;) {
          const { done, value } = await reader.read();
          if (done) break;
          acc += decoder.decode(value, { stream: true });
          setInsight(acc);
          setLoading(false); // first chunk → swap spinner for text
        }
      } catch (e) {
        if (e.name !== 'AbortError') setError(e.message);
      } finally {
        setLoading(false);
      }
    })();

    return () => controller.abort();
  }, [tile.id]);

  const node = (
    <div style={overlay} onClick={onClose}>
      <div style={panel} onClick={(e) => e.stopPropagation()}>
        <style>{`@keyframes blink { 50% { opacity: 0; } }`}</style>
        <div style={header}>
          <span style={{ fontSize: 18 }}>✨</span>
          <div style={{ flex: 1, minWidth: 0 }}>
            <div style={{ fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em', color: 'var(--muted)' }}>AI insight</div>
            <div style={{ fontSize: 15, fontWeight: 700, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{tile.title || 'This tile'}</div>
          </div>
          <button style={closeBtn} onClick={onClose}>✕</button>
        </div>

        <div style={body}>
          {error ? (
            <div style={{ color: 'var(--error)', fontSize: 14, lineHeight: 1.5 }}>⚠ {error}</div>
          ) : loading && !insight ? (
            <div style={{ color: 'var(--muted)', fontSize: 14, display: 'flex', alignItems: 'center', gap: 8 }}>
              <span style={{ animation: 'spin 1s linear infinite', display: 'inline-block' }}>⏳</span>
              Analysing this tile…
              <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
            </div>
          ) : (
            <div style={{ fontSize: 14, lineHeight: 1.65, color: 'var(--text)' }}>
              {renderMarkdownish(insight)}
              {loading && <span style={cursor} />}
            </div>
          )}
        </div>

        <div style={{ padding: '10px 18px', borderTop: '1px solid #eee', fontSize: 11, color: 'var(--muted)' }}>
          Generated by Claude from this tile's data. Verify important figures.
        </div>
      </div>
    </div>
  );

  return createPortal(node, document.body);
}

// Light rendering: "- " bullets and **bold**.
function renderMarkdownish(text) {
  if (!text) return null;
  return text.split('\n').filter((l) => l.trim()).map((line, i) => {
    const bulleted = /^[-*]\s+/.test(line.trim());
    const content = line.trim().replace(/^[-*]\s+/, '');
    const parts = content.split(/(\*\*[^*]+\*\*)/g).map((p, j) =>
      p.startsWith('**') && p.endsWith('**') ? <strong key={j}>{p.slice(2, -2)}</strong> : p
    );
    return (
      <div key={i} style={{ display: 'flex', gap: 8, marginBottom: 8 }}>
        {bulleted && <span style={{ color: 'var(--brand)' }}>•</span>}
        <span>{parts}</span>
      </div>
    );
  });
}

const overlay = { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.35)', display: 'flex', justifyContent: 'flex-end', zIndex: 400 };
const panel = { width: 'min(460px, 92vw)', height: '100%', background: '#fff', boxShadow: '-4px 0 24px rgba(0,0,0,0.15)', display: 'flex', flexDirection: 'column' };
const header = { display: 'flex', alignItems: 'center', gap: 12, padding: '16px 18px', borderBottom: '1px solid #e0e0e0' };
const body = { flex: 1, minHeight: 0, overflowY: 'auto', padding: 18 };
const closeBtn = { border: 'none', background: 'transparent', cursor: 'pointer', fontSize: 17, color: '#888' };
const cursor = { display: 'inline-block', width: 7, height: 15, background: 'var(--brand)', marginLeft: 2, verticalAlign: 'text-bottom', animation: 'blink 1s step-end infinite' };
